### ISSUE TITLE
[PE-D][Tester A] Input format not shown completely.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-F14-3/tp#113]
![Screenshot 2024-04-05 at 5.00.01 PM.png](https://raw.githubusercontent.com/CXIA17/ped/main/files/abcbbfd2-c4ce-4abf-b38e-362839c84d3a.png)

### The scrolling bar is not really working inside the pdf, maybe try to make the command shorter.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: CXIA17/ped#1

**Comment by V4Vern** [comment]
Added a command summary in the new UserGuide. This can help to resolve the above issue.

![image](https://github.com/AY2324S2-CS2113-F14-3/tp/assets/28131050/0e8ba81f-b8a3-49a8-ad72-c1df416af61c)
