### ISSUE TITLE
[PE-D][Tester C] Usage of special characters

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-F14-3/tp#118]
Possibly a minor bug - parsing of input for commands uses "/" as delimiter and prevents it from being read as string for name of workout or exercise etc and program thinks that string input is empty. If my exercise or workout somehow includes "/" in the name, I may not know as a user that special characters are not allowed by reading the error message or the UG.

![image.png](https://raw.githubusercontent.com/blackmirag3/ped/main/files/2cb2cec1-2381-44f9-b47f-8ed2edab950e.png)

Pretty sure you guys accounted for it with the no special characters error message when I use other special characters, so that's great.

Perhaps possible improvements to consider are explicitly adding this rule to the UG and printing a more concise error message :^)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: blackmirag3/ped#1

**Comment by joshualeejunyi** [comment]
Similar to #110
