### ISSUE TITLE
[PE-D][Tester D] User Guide code block issue

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-F14-3/tp#122]
![image.png](https://raw.githubusercontent.com/cirelesna/ped/main/files/102a69c4-69ae-41ec-8754-a36773dd1119.png)

Unable to see full command template in pdf

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: cirelesna/ped#3

**Comment by V4Vern** [comment]
Added a command summary in the new UserGuide. This can help to resolve the above issue.

![image](https://github.com/AY2324S2-CS2113-F14-3/tp/assets/28131050/50b5b36c-86fa-4d08-9152-a09675908f1f)
