### ISSUE TITLE
[PE-D][Tester A] Cannot assign workout to program

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-F14-3/tp#123]
![Screenshot 2024-04-05 at 5.17.36 PM.png](https://raw.githubusercontent.com/CXIA17/ped/main/files/e3642e37-dc65-453a-9815-7818e542c48a.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: CXIA17/ped#3

**Comment by V4Vern** [comment]
I think you might have seen wrongly in the user guide. It clearly states that the command is "**program /assign <WORKOUT_PLAN_NAME [string]> /to <DAY [string]>**" . You have missed out the "**/**" for the "**to**" arguments.

Below is an image of the UserGuide showing the correct command.

![image](https://github.com/AY2324S2-CS2113-F14-3/tp/assets/28131050/52b4a23d-effc-4e42-9a95-9adb030b6235)
