### ISSUE TITLE
Changing workout to 31st Feb in data.json allowed, causes crash when attempting to view

### ISSUE THREAD

**Issue by pqienso** [AY2324S2-CS2113-F14-3/tp#174]
By changing the exercise log date in `data.json` to 31st Feburary and running `program /history 2024-02-31`:
![Screenshot 2024-04-14 205058](https://github.com/AY2324S2-CS2113-F14-3/tp/assets/85116669/6c3a1d4c-d6cc-4e00-aa0f-8017b17bc86e)
`data.json` loads as usual (not desired behaviour).
A nullPointerException is thrown and the program crashes

**Comment by joshualeejunyi** [comment]
Fixed in #175

**Comment by joshualeejunyi** [comment]
Fixed in #175
