### ISSUE TITLE
code review for joshualeejunyi

### ISSUE THREAD

**Issue by yicheng-toh** [AY2324S2-CS2113-F14-3/tp#63]
Currently the execution of function does the following steps:
1. Execute logic
2. Print message

You might want to consider looking at [past tp](https://github.com/AY2324S1-CS2113-T17-1/tp/tree/master) or [AB3](https://github.com/se-edu/addressbook-level3) where they return a string as a response and outsource the printing to another class.

Do remember to remove [dead codes](https://nus-cs2113-ay2324s2.github.io/website/se-book-adapted/chapters/codeQuality.html#delete-dead-code).
<img width="198" alt="image" src="https://github.com/AY2324S2-CS2113-F14-3/tp/assets/75836313/04b0d90b-239a-4464-b472-5d69f39a8d4c">

If you have time, you could consider putting constants into another file to reduce the number of magic strings present.

Good use of guard clauses throughout the code.

**Comment by joshualeejunyi** [comment]
Sorry @yicheng-toh, could I check which function you are referring to for the first part? Thanks!

**Comment by yicheng-toh** [comment]
<img width="516" alt="image" src="https://github.com/AY2324S2-CS2113-F14-3/tp/assets/75836313/7717a260-f61b-491d-9677-a953c2eb811f">
In the execution functions, it is executing the logic and printing messages using the UI class after that. 
One side effect of that would be that the UI class is called to multiple classes resulting in redundant dependencies between the classes. Look at [coupling](https://nus-cs2113-ay2324s2.github.io/website/se-book-adapted/chapters/designFundamentals.html#coupling)

**Comment by yicheng-toh** [comment]
You may also want to put javadocs on your functions too.
