### ISSUE TITLE
code review for pqienso

### ISSUE THREAD

**Issue by yicheng-toh** [AY2324S2-CS2113-F14-3/tp#64]
<img width="518" alt="image" src="https://github.com/AY2324S2-CS2113-F14-3/tp/assets/75836313/70dbf176-af90-4f34-9447-cfe034331d29">

parser.getAction() gets repeated a couple of times, perhaps you could declare a variable for this value instead?

<img width="354" alt="image" src="https://github.com/AY2324S2-CS2113-F14-3/tp/assets/75836313/f5764ad9-efcc-437f-b642-0b560f7af75f">
Should it be 'assigned' instead of assign?

<img width="467" alt="image" src="https://github.com/AY2324S2-CS2113-F14-3/tp/assets/75836313/5f865104-5c2e-41a6-b33b-8cb5c871e3c3">

Perhaps you would like to consider to [avoid complicated expressions](https://nus-cs2113-ay2324s2.github.io/website/se-book-adapted/chapters/codeQuality.html#avoid-complicated-expressions)

similar to joshualeejunyi

Perhaps you might want to consider returing a string after executing the command for the UI to print the returned string.

<img width="322" alt="image" src="https://github.com/AY2324S2-CS2113-F14-3/tp/assets/75836313/7bba66eb-d98c-4023-8dd5-30ce6c730306">

You might want to take note of magic strings that are present in the codebase.

You could consider looking at [past tp](https://github.com/AY2324S1-CS2113-T17-1/tp/tree/master) or [AB3](https://github.com/se-edu/addressbook-level3) for inspiration.

**Comment by joshualeejunyi** [comment]
Regarding the "assigned" vs "assign", it is because the command is meant to be `week /assign <workout name> /to <day>`.
