### ISSUE TITLE
Incorrect listing order of exercises & workout

### ISSUE THREAD

**Issue by V4Vern** [AY2324S2-CS2113-F14-3/tp#69]
![photo_2024-03-27_09-38-07](https://github.com/AY2324S2-CS2113-F14-3/tp/assets/28131050/42b771b8-ecec-4741-a6cf-8ee0d4edef12)

It is supposed to be:

Listing Workouts:
1. test
2. test2

**Comment by LWachtel1** [comment]
"Java HashSet class implements the Set interface, backed by a hash table which is actually a [HashMap](https://www.geeksforgeeks.org/java-util-hashmap-in-java/) instance. **No guarantee is made as to the iteration order of the hash sets which means that the class does not guarantee the constant order of elements over time.**"

https://www.geeksforgeeks.org/hashset-in-java/
