### ISSUE TITLE
code review for LWachtel1

### ISSUE THREAD

**Issue by yicheng-toh** [AY2324S2-CS2113-F14-3/tp#86]
<img width="390" alt="image" src="https://github.com/AY2324S2-CS2113-F14-3/tp/assets/75836313/3e188e7d-e8d8-4f35-a1bb-eaf6c5b5efb4">

Perhaps you could consider dealing with [magic literals](https://nus-cs2113-ay2324s2.github.io/website/se-book-adapted/chapters/refactoring.html#how) in the code.

However, there is not sufficient code for me to do a proper review. (27 as of 31/03/24 2am GMT+8) 

If you are aiming for the highest tier, there should be more than 300 functional codes written by now. The tP contribution per student is classified into the following categories. Do note that only code that are in the main branch of the tP repo for your team is only considered.

<img width="548" alt="image" src="https://github.com/AY2324S2-CS2113-F14-3/tp/assets/75836313/0cb2f002-9563-4a15-a742-924c69cc8504">

These details can be gathered from the [course website](https://nus-cs2113-ay2324s2.github.io/website/admin/tp-grading.html#tp-grading).

You could check your contribution on the [dashboard](https://nus-cs2113-ay2324s2.github.io/tp-dashboard/?search=&sort=groupTitle&sortWithin=title&since=2024-02-23&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=true&tabOpen=true&tabType=authorship&tabAuthor=LWachtel1&tabRepo=AY2324S2-CS2113-F14-3%2Ftp%5Bmaster%5D&authorshipIsMergeGroup=false&authorshipFileTypes=functional-code&authorshipIsBinaryFileTypeChecked=false&authorshipIsIgnoredFilesChecked=false&checkedFileTypes=functional-code).

Should you require some assistance, you could consider putting it in the [forum](https://github.com/nus-cs2113-AY2324S2/forum/issues).

**Comment by LWachtel1** [comment]
Thanks for your feedback!
